// Question : Conditional Tests Write a series of conditional tests. Print a statement describing each test and your prediction for the results of each test.
var car = 'bmw';
console.log("Car is ".concat(car));
console.log("Is car == 'bmw'? I predict true");
console.log(car == 'bmw');
console.log("Is car == 'audi'? I predict false");
console.log(car == 'audi');
console.log(" ");
car = 'Ford Mustang';
console.log("Car is ".concat(car));
console.log("Is car == 'Ford Mustang'? I predict true");
console.log(car == 'Ford Mustang');
console.log("Is car == 'Nissan'? I predict false");
console.log(car == 'Nissan');
console.log(" ");
car = 'Nissan Skyline';
console.log("Car is ".concat(car));
console.log("Is car == 'Nissan Skyline'? I predict true");
console.log(car == 'Nissan Skyline');
console.log("Is car == 'Dodge'? I predict false");
console.log(car == 'Dodge');
console.log(" ");
car = "Toyota Corolla";
console.log("Car is ".concat(car));
console.log("Is car == 'Toyota Corolla'? I predict true");
console.log(car == 'Toyota Corolla');
console.log("Is car == 'Honda'? I predict false");
console.log(car == 'Honda');
console.log(" ");
car = 'Honda Civic';
console.log("Car is ".concat(car));
console.log("Is car == 'Honda Civic'? I predict true");
console.log(car == 'Honda Civic');
console.log("Is car == 'Toyota Corolla'? I predict false");
console.log(car == 'Toyota Corolla');
